version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    commit-message: 
      prefix: "npm | "
    labels: 
      - "dependabot"
    schedule:
      interval: "daily"
    assignees:
      - "xAtsuUC"
